name: Atualizar Badge de Progresso

on:
  push:
    branches:
      - main 

jobs:
  updateBadge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Atualizar Badge de Progresso
        run: |
          # Lógica para atualizar o progresso do projeto
        
          owner="AndreLuizRibeiro"
          repo="Template"
        
          response=$(curl -s "https://api.github.com/repos/$owner/$repo")
      
          total_issues=$(echo "$response" | jq '.open_issues_count')
          total_pulls=$(echo "$response" | jq '.open_pull_issues_count')
         
          closed_issues=$(echo "$response" | jq '.closed_issues')
          closed_pulls=$(echo "$response" | jq '.closed_pull_issues')
          
          progresso_issues=$(bc <<< "scale=2; ($closed_issues / ($closed_issues + $total_issues)) * 100")
          progresso_pulls=$(bc <<< "scale=2; ($closed_pulls / ($closed_pulls + $total_pulls)) * 100")
                       
          sed -i "s/Progresso: [0-9]*%/Progresso: ${progresso_issues}%/" README.md
          sed -i "s/Progresso: [0-9]*%/Progresso: ${progresso_pulls}%/" README.md
      
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add README.md
          git commit -m "Atualizar progresso do projeto [skip ci]"
          git push
          
